version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  
  be:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  fe:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - be